name: smile_activities_lambda
publish: 'none'
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  aws_lambda_dart_runtime: ^1.1.0
  aws_dynamodb_api: ^1.2.0
  http_methods: ^1.1.0
  uuid: ^3.0.6
  dio: ^4.0.6
dev_dependencies:
  build_runner:
  test: ^1.16.8